- hosts: rcos
  remote_user: root
  gather_facts: false
  vars:
    - log_file: "/opt/observatory.log"
    - server_dir: "/opt/observatory/"
    - port: 8443
  tasks:
    - local_action: shell grunt build --force

    - synchronize:
        src: ../dist/
        dest: /opt/observatory

    - shell: "forever stopall"
      args:
        executable: /bin/bash

    - npm:
        path: "{{ server_dir }}"
      ignore_errors: true

    - shell: "NODE_ENV=production PORT={{ port }} forever -a -l {{ log_file }} start {{ server_dir }}server/app.js"
